name: pagoo
channels: 
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - curl
  - wget=1.20.1
  - unzip
  - roary=3.13.0
  - r-base=4.0.3
  - r-devtools=2.3.2
  - r-tidyverse=1.3.0
  - r-phangorn=2.5.5
  - r-ggnewscale=0.4.5
  - r-tidytree=0.3.3
  - bioconductor-ggtree=2.4.0
  - bioconductor-decipher=2.18.0
