name: pagoo
channels: 
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - curl
  - wget=1.20.1
  - unzip
  - roary=3.13.0
  - r-base
  - r-devtools
  - r-tidyverse
  - r-phangorn
  - r-ggnewscale
  - r-tidytree
  - bioconductor-ggtree
  - bioconductor-decipher
